server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://jlab.tk/
    username:
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true