server:
  port: 8081

spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://jlab.tk/
#    username:
#    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true